#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor4,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motor1,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motor1] = 50;
	wait10Msec(10);

	motor[motor2] = 50;
	wait10Msec(10);

	motor[motor3] = 50;
	wait10Msec(10);

	motor[motor4] = 50;
	wait10Msec(10);
}
