#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor4,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     armMotor1,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_2,     armMotor2,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    goalGripper,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    armServo1,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    armServo2,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "StuffedGriffinsFunctions.c"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		nxtDisplayCenteredTextLine(3, "Encoder values:");
		nxtDisplayCenteredTextLine(4, "%d and %d ", nMotorEncoder[armMotor1], nMotorEncoder[armMotor2]);

		if(joy1Btn(5) == 1)
		{
			motor[armMotor1] = -10;
			motor[armMotor2] = -10;
		}
		else if(joy1Btn(7) == 1)
		{
			motor[armMotor1] = 5;
			motor[armMotor2] = 5;
		}
		else
		{
			motor[armMotor1] = 0;
			motor[armMotor2] = 0;
		}
	}
}
