#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor4,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motor1,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#pragma DebuggerWindows("joystickGame")
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

//Drive forward function
//time_seconds = How many seconds you want it to drive
//X = X speed
//Y = Y speed
//R = Rotation speed
void autoDrive (int time_seconds, int X, int Y, int R)
{
	//Drive
	motor[motor2] = -Y + R - X;
	motor[motor3] =  -Y + R + X;
	motor[motor1] = -Y - R + X;
	motor[motor4] =  -Y - R - X;

	//wait for _ seconds
	wait10Msec(100*time_seconds);

	//Reset motors
	motor[motor1] = 0;
	motor[motor4] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;

	return;
}

//Drive in the direction of the angle
//angle = angle to drive in, in degrees, (0 is forward, 90 is right, 180 is backwards, -90 is left, etc...)
//power = the power to drive with
//

void driveAngle( float angle, float power, float sec )
{
	//calculate X and Y power
	float Y = sinDegrees(90-angle)*power;
	float X = cosDegrees(angle)*power;
	//drive
	motor[motor1] = -Y-X;
	motor[motor4] = -Y+X;
	motor[motor2] = -Y+X;
	motor[motor3] = -Y-X;
	//wait for sec seconds
	wait10Msec(sec*100);

	//Reset motors
	motor[motor1] = 0;
	motor[motor4] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	//Create "deadzone" variables. Adjust threshold value to increase/decrease deadzone
	int X2 = 0, Y1 = 0, X1 = 0, Y2 = 0, threshold = 10;
	int mid = 95, var = 40;


	while (true)
	{
		//Create "deadzone" for Y1/Ch3
		if(abs(joystick.joy1_y1) > threshold)
			Y1 = -joystick.joy1_y1;
		else
			Y1 = 0;
		//Create "deadzone" for Y2/Ch2
		if(abs(joystick.joy1_y2) > threshold)
			Y2 = -joystick.joy1_y2;
		else
			Y2 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(joystick.joy1_x1) > threshold)
			X1 = joystick.joy1_x1;
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(joystick.joy1_x2) > threshold)
			X2 = joystick.joy1_x2;
		else
			X2 = 0;

		if(joystick.joy1_TopHat == 1)
		{
			autoDrive(1,0,50,50);

		}


		motor[motor1] = Y1-X1;
		motor[motor4] = Y1+X1;

		motor[motor2] = Y2+X2;
		motor[motor3] = Y2-X2;

	}
}
