#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		eraseDisplay();
		nxtDisplayCenteredTextLine(3, "IR value:");
		nxtDisplayCenteredTextLine(4, "%d", SensorValue[IR]);
		wait10Msec(1);
	}
}
