#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor4,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     armMotor1,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_2,     armMotor2,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    goalGripper,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    armServo1,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    armServo2,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "StuffedGriffinsFunctions.c" //include file with the Stuffed Griffins' functions

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	//declare variables
	int X2 = 0, Y1 = 0, X1 = 0, Y2 = 0;
	int down = 180;
	int up = 130;
	int arm2Up = 100, arm2Down = 0, arm2Default = 80, arm2 = 0;
	int armSpeed = 0, conveyerSpeed =0;
	int leftSpeed = 0, rightSpeed = 0;
	bool driveToggle = false;
	bool slowDrive = false;

	while (true)
	{
		//update joystick settings and set joystick variables
		getJoystickSettings(joystick);
		Y1 = -joystick.joy1_y1;
		X1 = joystick.joy1_x1;
		X2 = joystick.joy1_x2;
		Y2 = -joystick.joy1_y2;

		//create toggle for slow drive.  use button 5 to toggle.
		if(joy1Btn(9) == 1)
		{
			slowDrive=false;

		};
		if(joy1Btn(10) == 1)
		{
			slowDrive=true;
		};

		nxtDisplayCenteredTextLine(4, "%d", driveToggle);


		//--------Motors-------
		if(slowDrive){
			leftSpeed = joystick.joy1_y1;
			rightSpeed = joystick.joy1_y2

			;
			}else{
			leftSpeed = Y2/2 ;
			rightSpeed = Y1/2;
		}

		motor[motor1] = -leftSpeed;
		motor[motor2] = -leftSpeed;
		motor[motor3] = -rightSpeed;
		motor[motor4] = rightSpeed;

		//Arm
		//afarmSpeed = joystick.joy2_y2;

		armSpeed=joystick.joy2_y1;

		motor[armMotor1]=armSpeed;
		motor[armMotor2]=armSpeed;


		//intake control, second controller left y-axis
		motor[intake] = scale(joystick.joy2_y1, 5, 5, 100);

		motor[conveyor] = joystick.joy2_y2;

		//--------Servos-------

		//goal gripper control, second controller left bumper releases the goal, second controller left trigger engages the goal
		if(joy2Btn(5) == 1)
		{
			servo[goalGripper] = up;
		}
		if(joy2Btn(7) == 1)
		{
			servo[goalGripper] = down;
		}
		//Controling the arm servos.
		if(joy2Btn(1) == 1){
			arm2+=10;
			}else if(joy2Btn(2) == 1){
			arm2-=10;
		}

		if(joy2Btn(3) == 1){
			;
		}

		//Arm servo stuff!!
		servo[armServo1] = arm2;
		servo[armServo2] = -arm2+230;

	}
}
