#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor4,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    goalGripper,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "StuffedGriffinsFunctions.c" //include drive files

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	//declare variables
	int X2 = 0, Y1 = 0, X1 = 0, Y2 = 0;
	int down = 100;
	int up = 5;
	bool driveToggle = false;
	bool press = false;

	while (true)
	{
		//update joystick
		getJoystickSettings(joystick);
		Y1 = -joystick.joy1_y1;
		X1 = joystick.joy1_x1;
		X2 = joystick.joy1_x2;
		Y2 = -joystick.joy1_y2;

		int x = (X1+X2)/2;
		int y = (Y1+Y2)/2;

		//create toggle for slow drive.  use button 1 to toggle.
		if(joy1Btn(5) == 1 && press)
		{
			driveToggle=!driveToggle;
			press=false;
		}
		else if(joy1Btn(5) != 1)
		{
			press=true;
		}

		if(!driveToggle)
		{
			//normal drive with diagonal zones, first controller joysticks
			if( X1*Y1>=0 && X2*Y1>=0 && X1*Y2>=0 && X2*Y1>=0 && abs(x+y-10)/sqrt(2)-1.02*sqrt((x-10)*(x-10)+(y-10)*(y-10))-3>0 )
			{

				float average = scale((X1+Y1+X2+Y2)/4);
				motor[motor1] = average;
				motor[motor2] = 0;
				motor[motor3] = average;
				motor[motor4] = 0;

			}
			else if( -X1*Y1>=0 && -X2*Y1>=0 && -X1*Y2>=0 && -X2*Y1>=0 && abs(x+y-10)/sqrt(2)-1.02*sqrt((x-10)*(x-10)+(y-10)*(y-10))-3>0 )
			{
				float average = scale((-X1+Y1-X2+Y2)/4);
				motor[motor1] = 0;
				motor[motor2] = average;
				motor[motor3] = 0;
				motor[motor4] = average;
			}
			else
			{
				motor[motor1] = scale(Y2+X2);
				motor[motor4] = scale(Y2-X2);

				motor[motor2] = scale(Y1-X1);
				motor[motor3] = scale(Y1+X1);
			}
		}
		else //slow drive, no diagonal zones, first controller joysticks
		{
			motor[motor1] = scale(Y1+X1, 7, 5, 35);
			motor[motor4] = scale(Y1-X1, 7, 5, 35);

			motor[motor2] = scale(Y2-X2, 7, 5, 35);
			motor[motor3] = scale(Y2+X2, 7, 5, 35);
		}

		//intake control, second controller left y-axis
		motor[intake] = scale(joystick.joy2_y1, 5, 5, 100);

		//goal gripper control, second controller left bumper moves up, second controller left trigger moves down
		if(joy2Btn(5) == 1)
		{
			servo[goalGripper] = up;
		}
		if(joy2Btn(7) == 1)
		{
			servo[goalGripper] = down;
		}

	}
}
