#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor4,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    goalGripper,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    armServo,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    Robot Testing
//
// This file contains the testing files of various nondrive functions.
// This is the place to test new robot parts functions and such.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "StuffedGriffinsFunctions.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

//this task is designed for team 8489's arm, it should move it to different positions.
//the positions are defined by encoder distance form position 1.  There are four positions.
//There must be global variables currentPosition and newPosition, which stores the current
//and desired arm positions, respectivly.

//the variables pos1, pos2, pos3, and pos4 are the encoder ticks away from position 1(all the way down),
//to the desired position

int moveArm(int newPosition, int currentPosition)
{
  //the motor positions are encoder ticks from the bottom position
  //the servo positions are the locations of the servo in each different position
  int motorPos0 = 0, motorPos1 = 50, motorPos2 = 100;
  int servoPos0 = 10, servoPos1 = 25, servoPos2 = 50;

  //the positions are then put in arrays to make later computation easier
  int motorPositions[3] = {motorPos0, motorPos1, motorPos2};
  int servoPositions[3] = {servoPos0, servoPos1, servoPos2};

  //determine how many encoder ticks the motor needs to move

  int motorMovement = motorPositions[newPosition] - motorPositions[currentPosition];

  //start moving the servo to its position
  servo[arm] = servoPositions[newPosition];

  //reset the encoder
  nMotorEncoder[arm] = 0;

  //determine which way the motor needs to run
  if(motorMovement > 0)
  {
    motor[arm] = 50;

    //waiting for the target to be reached
    while(nMotorEncoder[arm] < motorMovement)
    {
      //carryout other commands
      teleopMecanumDrive();
      //TODO: functions that carry out non drive and non arm commands
    }
  }
  else if(motorMovement < 0)
  {
    motor[arm] = -50;

    //waiting for the target to be reached
    while(nMotorEncoder[arm] <= -motorMovement)
    {
      //carryout other commands
      teleopMecanumDrive();
      //TODO: functions that carry out non drive and arm commands
    }
  }

  //stop the motor
  motor[arm] = 0;

  //return the new position for the arm
  return newPosition;
}




/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase
	int down = 100;
	int up = 5;
	bool servoToggle = false;
	bool press = false;
	int armPosition = 0;

	while (true)
	{
		getJoystickSettings(joystick);

		//drive intake
		motor[intake] = scale(joystick.joy1_y1);

		//goal gripper
		if(joystick.joy1_TopHat == 0)
		{
			servoTarget[goalGripper] = up;
		}
		if(joystick.joy1_TopHat == 4)
		{
			servoTarget[goalGripper] = down;
		}

		//thomas' goal gripper one button toggle
		if(joy1Btn(4) == 1 && press)
		{
			servoToggle=!servoToggle;
			press=false;
		}
		else if(joy1Btn(4) != 1)
		{
			press=true;
		}

		if(servoToggle == false)
		{
			servo[goalGripper] = down;
		}
		else if(servoToggle == true)
		{
			servo[goalGripper] = up;
		}

		//need to test.
		//arm motor
		//triggered by buttons 1-3

		//check if button has been pressed
		if(joy1Btn(1) == 1)
		{
			armPosition = moveArm(0, armPosition);
		}
		else if(joy1Btn(2) == 1)
		{
			armPosition = moveArm(1, armPosition);
		}
		else if(joy1Btn(3) == 1)
		{
			armPosition = moveArm(2, armPosition);
		}

		//this button moves the arm motor down in case the arm is thrown off
    if(joy1Btn(7) == 1)
    {
    	motor[arm] = -25;
    }
    else
    {
    	motor[arm] = 0;
    }

	}

}
