#pragma config(Sensor, S4,     ultraSonic,     sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int a = 0;
	while(true)
	{
		a = SensorValue[S4];
	  nxtDisplayCenteredTextLine(3, "ultrasonic value:");
	  nxtDisplayCenteredTextLine(4, "%d", a);
		wait10Msec(1);
	}

}
